/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32F0X)
#include <stm32f0xx_ll_tim.h>
#elif defined(CONFIG_SOC_SERIES_STM32F1X)
#include <stm32f1xx_ll_tim.h>
#endif
