/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32C0X)
#include <stm32c0xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32G0X)
#include <stm32g0xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32G4X)
#include <stm32g4xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32L4X)
#include <stm32l4xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32L5X)
#include <stm32l5xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32MP13X)
#include <stm32mp13xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32MP1X)
#include <stm32mp1xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32U0X)
#include <stm32u0xx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32WB0X)
#include <stm32wb0x_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32WBX)
#include <stm32wbxx_ll_dmamux.h>
#elif defined(CONFIG_SOC_SERIES_STM32WLX)
#include <stm32wlxx_ll_dmamux.h>
#endif
