/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <autoconf.h>

#if defined(CONFIG_SOC_SERIES_STM32F4X)
#include <stm32f4xx_ll_dma2d.h>
#elif defined(CONFIG_SOC_SERIES_STM32F7X)
#include <stm32f7xx_ll_dma2d.h>
#elif defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_dma2d.h>
#elif defined(CONFIG_SOC_SERIES_STM32L4X)
#include <stm32l4xx_ll_dma2d.h>
#endif
