/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <autoconf.h>

#if defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_mdma.h>
#endif
