/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32G4X)
#include <stm32g4xx_ll_fmac.h>
#elif defined(CONFIG_SOC_SERIES_STM32H5X)
#include <stm32h5xx_ll_fmac.h>
#elif defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_fmac.h>
#elif defined(CONFIG_SOC_SERIES_STM32U5X)
#include <stm32u5xx_ll_fmac.h>
#endif
