/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_swpmi.h>
#elif defined(CONFIG_SOC_SERIES_STM32L4X)
#include <stm32l4xx_ll_swpmi.h>
#endif
