/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32F1X)
#include <stm32f1xx_ll_fsmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32F2X)
#include <stm32f2xx_ll_fsmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32F4X)
#include <stm32f4xx_ll_fsmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32L1X)
#include <stm32l1xx_ll_fsmc.h>
#endif
