/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32H5X)
#include <stm32h5xx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32H7RSX)
#include <stm32h7rsxx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32L4X)
#include <stm32l4xx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32L5X)
#include <stm32l5xx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32MP2X)
#include <stm32mp2xx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32N6X)
#include <stm32n6xx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32U3X)
#include <stm32u3xx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32U5X)
#include <stm32u5xx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32WB0X)
#include <stm32wb0x_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32WBAX)
#include <stm32wbaxx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32WBX)
#include <stm32wbxx_ll_pka.h>
#elif defined(CONFIG_SOC_SERIES_STM32WLX)
#include <stm32wlxx_ll_pka.h>
#endif
