/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <autoconf.h>

#if defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_hsem.h>
#elif defined(CONFIG_SOC_SERIES_STM32MP1X)
#include <stm32mp1xx_ll_hsem.h>
#elif defined(CONFIG_SOC_SERIES_STM32WBX)
#include <stm32wbxx_ll_hsem.h>
#elif defined(CONFIG_SOC_SERIES_STM32WLX)
#include <stm32wlxx_ll_hsem.h>
#endif
