/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <autoconf.h>

#if defined(CONFIG_SOC_SERIES_STM32U5X)
#include <stm32u5xx_ll_lpgpio.h>
#endif
