/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_mdma.h>
#elif defined(CONFIG_SOC_SERIES_STM32MP13X)
#include <stm32mp13xx_ll_mdma.h>
#endif
