/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32F3X)
#include <stm32f3xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32F4X)
#include <stm32f4xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32F7X)
#include <stm32f7xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32G4X)
#include <stm32g4xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32H5X)
#include <stm32h5xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32H7RSX)
#include <stm32h7rsxx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32L4X)
#include <stm32l4xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32L5X)
#include <stm32l5xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32MP13X)
#include <stm32mp13xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32MP1X)
#include <stm32mp1xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32MP2X)
#include <stm32mp2xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32N6X)
#include <stm32n6xx_ll_fmc.h>
#elif defined(CONFIG_SOC_SERIES_STM32U5X)
#include <stm32u5xx_ll_fmc.h>
#endif
