/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_STM32F0X)
#include <stm32f0xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32F3X)
#include <stm32f3xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32G0X)
#include <stm32g0xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32G4X)
#include <stm32g4xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32H5X)
#include <stm32h5xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32H7X)
#include <stm32h7xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32L0X)
#include <stm32l0xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32L1X)
#include <stm32l1xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32L4X)
#include <stm32l4xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32L5X)
#include <stm32l5xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32U0X)
#include <stm32u0xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32U3X)
#include <stm32u3xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32U5X)
#include <stm32u5xx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32WBAX)
#include <stm32wbaxx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32WBX)
#include <stm32wbxx_ll_comp.h>
#elif defined(CONFIG_SOC_SERIES_STM32WLX)
#include <stm32wlxx_ll_comp.h>
#endif
