# series_list.cmake - list of supported STM32 series
#
# Autogenerated by autogenpackage.py - DO NOT EDIT MANUALLY!
#
# Copyright (c) 2025 STMicroelectronics

set(supported_series
  stm32c0x
  stm32f0x
  stm32f1x
  stm32f2x
  stm32f3x
  stm32f4x
  stm32f7x
  stm32g0x
  stm32g4x
  stm32h5x
  stm32h7rsx
  stm32h7x
  stm32l0x
  stm32l1x
  stm32l4x
  stm32l5x
  stm32mp13x
  stm32mp1x
  stm32mp2x
  stm32n6x
  stm32u0x
  stm32u3x
  stm32u5x
  stm32wb0x
  stm32wbax
  stm32wbx
  stm32wlx
)
