/**
  ******************************************************************************
  * @file    stm32mp2xx_hal.h
  * @author  MCD Application Team
  * @brief   This file contains all the functions prototypes for the HAL
  *          module driver.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __STM32MP2xx_HAL_H
#define __STM32MP2xx_HAL_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32mp2xx_hal_conf.h"

/** @addtogroup STM32MP2xx_HAL_Driver
  * @{
  */

/** @addtogroup HAL
  * @{
  */

/* Exported types ------------------------------------------------------------*/
/* Exported constants --------------------------------------------------------*/
/** @defgroup HAL_Exported_Constants HAL Exported Constants
  * @{
  */
/** @defgroup HDP_Mux HDP Mux
  * @{
  */
#define  HAL_HDP_MUX0                   (HDP_MUX_MUX0)
#define  HAL_HDP_MUX1                   (HDP_MUX_MUX1)
#define  HAL_HDP_MUX2                   (HDP_MUX_MUX2)
#define  HAL_HDP_MUX3                   (HDP_MUX_MUX3)
#define  HAL_HDP_MUX4                   (HDP_MUX_MUX4)
#define  HAL_HDP_MUX5                   (HDP_MUX_MUX5)
#define  HAL_HDP_MUX6                   (HDP_MUX_MUX6)
#define  HAL_HDP_MUX7                   (HDP_MUX_MUX7)
/**
  * @}
 */

/** @defgroup HDP_Signal  HDP Signal
  * @{
  */
/*Signal on HDP0 Mux/signal*/
#define  HAL_HDP_PWR_PWRWAKE_SYS          (0x00000000UL)
#define  HAL_HDP_CPU2_SLEEP_DEEP          (HDP_MUX_MUX0_0)
#define  HAL_HDP_BSEC_OUT_TEST_SDR_UNLOCK (HDP_MUX_MUX0_1)
#define  HAL_HDP_BSEC_OUT_NIDENM          (HDP_MUX_MUX0_1|HDP_MUX_MUX0_0)
#define  HAL_HDP_BSEC_OUT_NIDENA          (HDP_MUX_MUX0_2)
#define  HAL_HDP_CPU2_STATE_0             (HDP_MUX_MUX0_2|HDP_MUX_MUX0_0)
#define  HAL_HDP_RCC_PWRDS_SYS            (HDP_MUX_MUX0_2|HDP_MUX_MUX0_1)
#define  HAL_HDP_GPU_DBG7                 (HDP_MUX_MUX0_2|HDP_MUX_MUX0_1|HDP_MUX_MUX0_0)
#define  HAL_HDP_DDRSS_CSYSREQ_DDRC       (HDP_MUX_MUX0_3)
#define  HAL_HDP_DDRSS_DFI_PHYUPD_REQ     (HDP_MUX_MUX0_3|HDP_MUX_MUX0_0)
#define  HAL_HDP_CPU3_SLEEP_DEEP          (HDP_MUX_MUX0_3|HDP_MUX_MUX0_1)
#define  HAL_HDP_D2_GBL_PER_CLK_BUS_REQ   (HDP_MUX_MUX0_3|HDP_MUX_MUX0_1|HDP_MUX_MUX0_0)
#define  HAL_HDP_PCIE_USB_CXPL_EI_0       (HDP_MUX_MUX0_3|HDP_MUX_MUX0_2)
#define  HAL_HDP_PCIE_USB_CXPL_EI_8       (HDP_MUX_MUX0_3|HDP_MUX_MUX0_2|HDP_MUX_MUX0_0)
#define  HAL_HDP_D3_STATE_0               (HDP_MUX_MUX0_3|HDP_MUX_MUX0_2|HDP_MUX_MUX0_1)
#define  HAL_HDP_GPOVAL_0                 (HDP_MUX_MUX0_3|HDP_MUX_MUX0_2|HDP_MUX_MUX0_1|HDP_MUX_MUX0_0)

/*Signal on HDP1 Mux/signal*/
#define  HAL_HDP_PWR_PWRWAKE_CPU2       (0x00000000UL)
#define  HAL_HDP_CPU2_HALTED            (HDP_MUX_MUX1_0)
#define  HAL_HDP_CPU2_STATE_1           (HDP_MUX_MUX1_1)
#define  HAL_HDP_BSEC_OUT_DBGENM        (HDP_MUX_MUX1_1|HDP_MUX_MUX1_0)
#define  HAL_HDP_BSEC_OUT_DBGENA        (HDP_MUX_MUX1_2)
#define  HAL_HDP_EXTI1_SYS_WAKEUP       (HDP_MUX_MUX1_2|HDP_MUX_MUX1_0)
#define  HAL_HDP_RCC_PWRDS_CPU2         (HDP_MUX_MUX1_2|HDP_MUX_MUX1_1)
#define  HAL_HDP_GPU_DBG6               (HDP_MUX_MUX1_2|HDP_MUX_MUX1_1|HDP_MUX_MUX1_0)
#define  HAL_HDP_DDRSS_CSYSACK_DDRC     (HDP_MUX_MUX1_3)
#define  HAL_HDP_DDRSS_DFI_PHYMSTR_REQ  (HDP_MUX_MUX1_3|HDP_MUX_MUX1_0)
#define  HAL_HDP_CPU3_HALTED            (HDP_MUX_MUX1_3|HDP_MUX_MUX1_1)
#define  HAL_HDP_D2_GBL_PER_DMA_REQ     (HDP_MUX_MUX1_3|HDP_MUX_MUX1_1|HDP_MUX_MUX1_0)
#define  HAL_HDP_PCIE_USB_CXPL_EI_1     (HDP_MUX_MUX1_3|HDP_MUX_MUX1_2)
#define  HAL_HDP_PCIE_USB_CXPL_EI_9     (HDP_MUX_MUX1_3|HDP_MUX_MUX1_2|HDP_MUX_MUX1_0)
#define  HAL_HDP_D3_STATE_1             (HDP_MUX_MUX1_3|HDP_MUX_MUX1_2|HDP_MUX_MUX1_1)
#define  HAL_HDP_GPOVAL_1               (HDP_MUX_MUX1_3|HDP_MUX_MUX1_2|HDP_MUX_MUX1_1|HDP_MUX_MUX1_0)

/*Signal on HDP2 Mux/signal*/
#define  HAL_HDP_PWR_PWRWAKE_CPU1       (0x00000000UL)
#define  HAL_HDP_CPU2_RXEV              (HDP_MUX_MUX2_0)
#define  HAL_HDP_CPU1_NPMUIRQ1          (HDP_MUX_MUX2_1)
#define  HAL_HDP_CPU1_NFIQOUT1          (HDP_MUX_MUX2_1|HDP_MUX_MUX2_0)
#define  HAL_HDP_BSEC_OUT_SHDBGEN       (HDP_MUX_MUX2_2)
#define  HAL_HDP_EXTI1_CPU2_WAKEUP      (HDP_MUX_MUX2_2|HDP_MUX_MUX2_0)
#define  HAL_HDP_RCC_PWRDS_CPU1         (HDP_MUX_MUX2_2|HDP_MUX_MUX2_1)
#define  HAL_HDP_GPU_DBG5               (HDP_MUX_MUX2_2|HDP_MUX_MUX2_1|HDP_MUX_MUX2_0)
#define  HAL_HDP_DDRSS_CACTIVE_DDRC     (HDP_MUX_MUX2_3)
#define  HAL_HDP_DDRSS_DFI_LP_REQ       (HDP_MUX_MUX2_3|HDP_MUX_MUX2_0)
#define  HAL_HDP_CPU3_RXEV              (HDP_MUX_MUX2_3|HDP_MUX_MUX2_1)
#define  HAL_HDP_HPDMA1_CLK_BUS_REQ     (HDP_MUX_MUX2_3|HDP_MUX_MUX2_1|HDP_MUX_MUX2_0)
#define  HAL_HDP_PCIE_USB_CXPL_EI_2     (HDP_MUX_MUX2_3|HDP_MUX_MUX2_2)
#define  HAL_HDP_PCIE_USB_CXPL_EI_10    (HDP_MUX_MUX2_3|HDP_MUX_MUX2_2|HDP_MUX_MUX2_0)
#define  HAL_HDP_D3_STATE_2             (HDP_MUX_MUX2_3|HDP_MUX_MUX2_2|HDP_MUX_MUX2_1)
#define  HAL_HDP_GPOVAL_2               (HDP_MUX_MUX2_3|HDP_MUX_MUX2_2|HDP_MUX_MUX2_1|HDP_MUX_MUX2_0)

/*Signal on HDP3 Mux/signal*/
#define  HAL_HDP_PWR_SEL_VTH_VDDCPU     (0x00000000UL)
#define  HAL_HDP_CPU2_TXEV              (HDP_MUX_MUX3_0)
#define  HAL_HDP_CPU1_NPMUIRQ0          (HDP_MUX_MUX3_1)
#define  HAL_HDP_CPU1_NFIQOUT0          (HDP_MUX_MUX3_1|HDP_MUX_MUX3_0)
#define  HAL_HDP_BSEC_OUT_DDBGEN        (HDP_MUX_MUX3_2)
#define  HAL_HDP_EXTI1_CPU1_WAKEUP      (HDP_MUX_MUX3_2|HDP_MUX_MUX3_0)
#define  HAL_HDP_CPU3_STATE_0           (HDP_MUX_MUX3_2|HDP_MUX_MUX3_1)
#define  HAL_HDP_GPU_DBG4               (HDP_MUX_MUX3_2|HDP_MUX_MUX3_1|HDP_MUX_MUX3_0)
#define  HAL_HDP_DDRSS_MCDCG_EN         (HDP_MUX_MUX3_3)
#define  HAL_HDP_DDRSS_DFI_FREQ_0       (HDP_MUX_MUX3_3|HDP_MUX_MUX3_0)
#define  HAL_HDP_CPU3_TXEV              (HDP_MUX_MUX3_3|HDP_MUX_MUX3_1)
#define  HAL_HDP_HPDMA2_CLK_BUS_REQ     (HDP_MUX_MUX3_3|HDP_MUX_MUX3_1|HDP_MUX_MUX3_0)
#define  HAL_HDP_PCIE_USB_CXPL_EI_3     (HDP_MUX_MUX3_3|HDP_MUX_MUX3_2)
#define  HAL_HDP_PCIE_USB_CXPL_EI_11    (HDP_MUX_MUX3_3|HDP_MUX_MUX3_2|HDP_MUX_MUX3_0)
#define  HAL_HDP_D1_STATE_0             (HDP_MUX_MUX3_3|HDP_MUX_MUX3_2|HDP_MUX_MUX3_1)
/* Value of PWR_CPU1D1SR_DSTATE[1] bitfield */
#define  HAL_HDP_GPOVAL_3               (HDP_MUX_MUX3_3|HDP_MUX_MUX3_2|HDP_MUX_MUX3_1|HDP_MUX_MUX3_0)

/*Signal on HDP4 Mux/signal*/
#define  HAL_HDP_PWR_SEL_VTH_VDDCORE    (0x00000000UL)
#define  HAL_HDP_CPU2_SLEEPING          (HDP_MUX_MUX4_0)
#define  HAL_HDP_CPU1_EVENTO            (HDP_MUX_MUX4_1)
#define  HAL_HDP_CPU1_NIRQOUT1          (HDP_MUX_MUX4_1|HDP_MUX_MUX4_0)
#define  HAL_HDP_BSEC_OUT_SPNIDENA      (HDP_MUX_MUX4_2)
#define  HAL_HDP_EXTI2_D3_WAKEUP        (HDP_MUX_MUX4_2|HDP_MUX_MUX4_0)
#define  HAL_HDP_ETH1_OUT_PMT_INTR_O    (HDP_MUX_MUX4_2|HDP_MUX_MUX4_1)
#define  HAL_HDP_GPU_DBG3               (HDP_MUX_MUX4_2|HDP_MUX_MUX4_1|HDP_MUX_MUX4_0)
#define  HAL_HDP_DDRSS_DPHYCG_EN        (HDP_MUX_MUX4_3)
#define  HAL_HDP_DDRSS_OBSP0            (HDP_MUX_MUX4_3|HDP_MUX_MUX4_0)
#define  HAL_HDP_CPU3_SLEEPING          (HDP_MUX_MUX4_3|HDP_MUX_MUX4_1)
#define  HAL_HDP_HDPMA3_CLK_BUS_REQ      (HDP_MUX_MUX4_3|HDP_MUX_MUX4_1|HDP_MUX_MUX4_0)
#define  HAL_HDP_PCIE_USB_CXPL_EI_4     (HDP_MUX_MUX4_3|HDP_MUX_MUX4_2)
#define  HAL_HDP_PCIE_USB_CXPL_EI_12    (HDP_MUX_MUX4_3|HDP_MUX_MUX4_2|HDP_MUX_MUX4_0)
/* Value of PWR_CPU1D1SR_DSTATE[1] bitfield */
#define  HAL_HDP_D1_STATE_1             (HDP_MUX_MUX4_3|HDP_MUX_MUX4_2|HDP_MUX_MUX4_1)
#define  HAL_HDP_GPOVAL_4               (HDP_MUX_MUX4_3|HDP_MUX_MUX4_2|HDP_MUX_MUX4_1|HDP_MUX_MUX4_0)

/*Signal on HDP5 Mux/signal*/
#define  HAL_HDP_CPU1_STANDBYWFI_L2     (0x00000000UL)
#define  HAL_HDP_HDP5SIGNAL1_RESERVED   (HDP_MUX_MUX5_0)
#define  HAL_HDP_HDP5SIGNAL2_RESERVED   (HDP_MUX_MUX5_1)
#define  HAL_HDP_CPU1_NIRQOUT0          (HDP_MUX_MUX5_1|HDP_MUX_MUX5_0)
#define  HAL_HDP_BSEC_OUT_SPIDENA       (HDP_MUX_MUX5_2)
#define  HAL_HDP_EXTI2_CPU3_WAKEUP      (HDP_MUX_MUX5_2|HDP_MUX_MUX5_0)
#define  HAL_HDP_ETH1_OUT_LPI_INTR_O    (HDP_MUX_MUX5_2|HDP_MUX_MUX5_1)
#define  HAL_HDP_GPU_DBG2               (HDP_MUX_MUX5_2|HDP_MUX_MUX5_1|HDP_MUX_MUX5_0)
#define  HAL_HDP_DDRSS_DFI_INIT_START   (HDP_MUX_MUX5_3)
#define  HAL_HDP_DDRSS_OBSP1            (HDP_MUX_MUX5_3|HDP_MUX_MUX5_0)
#define  HAL_HDP_CPU3_STATE_1           (HDP_MUX_MUX5_3|HDP_MUX_MUX5_1)
#define  HAL_HDP_D3_GPL_CLK_BUS_REQ     (HDP_MUX_MUX5_3|HDP_MUX_MUX5_1|HDP_MUX_MUX5_0)
#define  HAL_HDP_PCIE_USB_CXPL_EI_5     (HDP_MUX_MUX5_3|HDP_MUX_MUX5_2)
#define  HAL_HDP_PCIE_USB_CXPL_EI_13    (HDP_MUX_MUX5_3|HDP_MUX_MUX5_2|HDP_MUX_MUX5_0)
/* Value of PWR_CPU1D1SR_DSTATE[2] bitfield */
#define  HAL_HDP_D1_STATE_2             (HDP_MUX_MUX5_3|HDP_MUX_MUX5_2|HDP_MUX_MUX5_1)
#define  HAL_HDP_GPOVAL_5               (HDP_MUX_MUX5_3|HDP_MUX_MUX5_2|HDP_MUX_MUX5_1|HDP_MUX_MUX5_0)

/*Signal on HDP6 Mux/signal*/
#define  HAL_HDP_CPU1_STANDBYWFI_1      (0x00000000UL)
#define  HAL_HDP_CPU1_STANDBYWFE_1      (HDP_MUX_MUX6_0)
#define  HAL_HDP_CPU1_HALTED_1          (HDP_MUX_MUX6_1)
#define  HAL_HDP_CPU1_NAXIER_RIRQ       (HDP_MUX_MUX6_1|HDP_MUX_MUX6_0)
#define  HAL_HDP_BSEC_OUT_SPNIDENM      (HDP_MUX_MUX6_2)
#define  HAL_HDP_EXTI2_CPU2_WAKEUP      (HDP_MUX_MUX6_2|HDP_MUX_MUX6_0)
#define  HAL_HDP_ETH2_OUT_PMT_INTR_O    (HDP_MUX_MUX6_2|HDP_MUX_MUX6_1)
#define  HAL_HDP_GPU_DBG1               (HDP_MUX_MUX6_2|HDP_MUX_MUX6_1|HDP_MUX_MUX6_0)
#define  HAL_HDP_DDRSS_DFI_INIT_CMPLT   (HDP_MUX_MUX6_3)
#define  HAL_HDP_DDRSS_OBSP2            (HDP_MUX_MUX6_3|HDP_MUX_MUX6_0)
#define  HAL_HDP_D2_STATE_0             (HDP_MUX_MUX6_3|HDP_MUX_MUX6_1)
#define  HAL_HDP_D3_GPL_PER_DMA_REQ     (HDP_MUX_MUX6_3|HDP_MUX_MUX6_1|HDP_MUX_MUX6_0)
#define  HAL_HDP_PCIE_USB_CXPL_EI_6     (HDP_MUX_MUX6_3|HDP_MUX_MUX6_2)
#define  HAL_HDP_PCIE_USB_CXPL_EI_14    (HDP_MUX_MUX6_3|HDP_MUX_MUX6_2|HDP_MUX_MUX6_0)
/* Value of PWR_CPU1D1SR_CSTATE[0] bitfield */
#define  HAL_HDP_CPU1_STATE_0           (HDP_MUX_MUX6_3|HDP_MUX_MUX6_2|HDP_MUX_MUX6_1)
#define  HAL_HDP_GPOVAL_6               (HDP_MUX_MUX6_3|HDP_MUX_MUX6_2|HDP_MUX_MUX6_1|HDP_MUX_MUX6_0)

/*Signal on HDP7 Mux/signal*/
#define  HAL_HDP_CPU1_STANDBYWFI_0      (0x00000000UL)
#define  HAL_HDP_CPU1_STANDBYWFE_0      (HDP_MUX_MUX7_0)
#define  HAL_HDP_CPU1_HALTED_0          (HDP_MUX_MUX7_1)
#define  HAL_HDP_HDP7SIGNAL3_RESERVED   (HDP_MUX_MUX7_1|HDP_MUX_MUX7_0)
#define  HAL_HDP_BSEC_OUT_SPIDENM       (HDP_MUX_MUX7_2)
#define  HAL_HDP_EXTI2_CPU1_WAKEUP      (HDP_MUX_MUX7_2|HDP_MUX_MUX7_0)
#define  HAL_HDP_ETH2_OUT_LPI_INTR_O    (HDP_MUX_MUX7_2|HDP_MUX_MUX7_1)
#define  HAL_HDP_GPU_DBG0               (HDP_MUX_MUX7_2|HDP_MUX_MUX7_1|HDP_MUX_MUX7_0)
#define  HAL_HDP_DDRSS_DFI_CTRLUPD_REQ  (HDP_MUX_MUX7_3)
#define  HAL_HDP_DDRSS_OBSP3            (HDP_MUX_MUX7_3|HDP_MUX_MUX7_0)
#define  HAL_HDP_D2_STATE_1             (HDP_MUX_MUX7_3|HDP_MUX_MUX7_1)
#define  HAL_HDP_LPDMA_CLK_BUS_REQ      (HDP_MUX_MUX7_3|HDP_MUX_MUX7_1|HDP_MUX_MUX7_0)
#define  HAL_HDP_PCIE_USB_CXPL_EI_7     (HDP_MUX_MUX7_3|HDP_MUX_MUX7_2)
#define  HAL_HDP_PCIE_USB_CXPL_EI_15    (HDP_MUX_MUX7_3|HDP_MUX_MUX7_2|HDP_MUX_MUX7_0)
/* Value of PWR_CPU1D1SR_CSTATE[1:0] bitfield */
#define  HAL_HDP_CPU1_STATE_1           (HDP_MUX_MUX7_3|HDP_MUX_MUX7_2|HDP_MUX_MUX7_1)
#define  HAL_HDP_GPOVAL_7               (HDP_MUX_MUX7_3|HDP_MUX_MUX7_2|HDP_MUX_MUX7_1|HDP_MUX_MUX7_0)

/**
  * @}
  */


/** @defgroup SYSCFG_Ethernet_Config  SYSCFG Ethernet Config
  * @{
  */

/*!< Select the Media Independent Interface */
#define SYSCFG_ETH_MII                      (0x0U << SYSCFG_ETH1CR_ETH1_SEL_Pos)

/*!< Select the reduced gigabit media-independent interface*/
#define SYSCFG_ETH_RGMII                    (0x1U << SYSCFG_ETH1CR_ETH1_SEL_Pos)

/*!< Select the Reduced Media Independent Interface */
#define SYSCFG_ETH_RMII                     (0x4U << SYSCFG_ETH1CR_ETH1_SEL_Pos)

#define IS_SYSCFG_ETHERNET_CONFIG(CONFIG) (((CONFIG) == SYSCFG_ETH_MII) || \
                                           ((CONFIG) == SYSCFG_ETH_RGMII) || \
                                           ((CONFIG) == SYSCFG_ETH_RMII))

/*!< Select the External clock */
#define SYSCFG_ETH_EXT_CLK                  (0x0U << SYSCFG_ETH1CR_ETH1_CLK_SEL_Pos)

/*!< Select the RCC Internal Clock */
#define SYSCFG_ETH_RCC_CLK                  (0x1U << SYSCFG_ETH1CR_ETH1_CLK_SEL_Pos)

#define IS_SYSCFG_ETHERNET_CLOCK_CONFIG(CONFIG) (((CONFIG) == SYSCFG_ETH_EXT_CLK) || \
                                                 ((CONFIG) == SYSCFG_ETH_RCC_CLK))

/**
  * @}
  */

#if defined(SYSCFG_IOCR_HSLVEN_TRACE)
/** @defgroup SYSCFG_Analog_Switch_Config SYSCFG Analog Switch Config
  * @{
  */
#define SYSCFG_SWITCH_PA0                            SYSCFG_IOCR_ANA0_SEL  /*!< Select PA0 analog switch */
#define SYSCFG_SWITCH_PA1                            SYSCFG_IOCR_ANA1_SEL  /*!< Select PA1 analog switch */

#define IS_SYSCFG_ANALOG_SWITCH(SWITCH)               ((((SWITCH) & SYSCFG_SWITCH_PA0) == SYSCFG_SWITCH_PA0)|| \
                                                       (((SWITCH) & SYSCFG_SWITCH_PA1) == SYSCFG_SWITCH_PA1))

#define SYSCFG_SWITCH_PA0_OPEN                       SYSCFG_IOCR_ANA0_SEL       /*!<  ANA0 internally connected to PA0 */
#define SYSCFG_SWITCH_PA0_CLOSE                      ((uint32_t)0x00000000)         /*!< PA0 analog is not connected */
#define SYSCFG_SWITCH_PA1_OPEN                       SYSCFG_IOCR_ANA1_SEL       /*!<  ANA1 internally connected to PA1 */
#define SYSCFG_SWITCH_PA1_CLOSE                      ((uint32_t)0x00000000)         /*!< PA1 is not connected*/

#define IS_SYSCFG_SWITCH_STATE(STATE)       ((((STATE) & SYSCFG_SWITCH_PA0_OPEN) == SYSCFG_SWITCH_PA0_OPEN)    || \
                                             (((STATE) & SYSCFG_SWITCH_PA0_CLOSE) == SYSCFG_SWITCH_PA0_CLOSE)  || \
                                             (((STATE) & SYSCFG_SWITCH_PA1_OPEN) == SYSCFG_SWITCH_PA1_OPEN)    || \
                                             (((STATE) & SYSCFG_SWITCH_PA1_CLOSE) == SYSCFG_SWITCH_PA1_CLOSE))
/**
  * @}
  */

/** @defgroup SYSCFG_IOControl_HSpeed_Config SYSCFG IOControl HighSpeed Config
  * @{
  */
#define SYSCFG_HIGHSPEED_TRACE_SIGNAL             SYSCFG_IOCR_HSLVEN_TRACE       /*!< High Speed Low Voltage Pad mode Enable when a TRACEx signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_LCD_SIGNAL               SYSCFG_IOCR_HSLVEN_LCD         /*!< High Speed Low Voltage Pad mode Enable when a LCDx signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_OCTOSPIM_P1_SIGNAL       SYSCFG_IOCR_HSLVEN_OCTOSPIM_P1 /*!< High Speed Low Voltage Pad mode Enable when a OCTOSPIM_P1_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_OCTOSPIM_P2_SIGNAL       SYSCFG_IOCR_HSLVEN_OCTOSPIM_P2 /*!< High Speed Low Voltage Pad mode Enable when a OCTOSPIM_P2_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_ETH1_SIGNAL              SYSCFG_IOCR_HSLVEN_ETH1        /*!< High Speed Low Voltage Pad mode Enable when a ETH1_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_ETH2_SIGNAL              SYSCFG_IOCR_HSLVEN_ETH2        /*!< High Speed Low Voltage Pad mode Enable when a ETH2_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_ETH3_SIGNAL              SYSCFG_IOCR_HSLVEN_ETH3        /*!< High Speed Low Voltage Pad mode Enable when a ETH3_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SDMMC3_SIGNAL            SYSCFG_IOCR_HSLVEN_SDMMC3      /*!< High Speed Low Voltage Pad mode Enable when a SDMMC3_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SPI1_SIGNAL              SYSCFG_IOCR_HSLVEN_SPI1        /*!< High Speed Low Voltage Pad mode Enable when a SPI1_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SPI2_SIGNAL              SYSCFG_IOCR_HSLVEN_SPI2        /*!< High Speed Low Voltage Pad mode Enable when a SPI2_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SPI3_SIGNAL              SYSCFG_IOCR_HSLVEN_SPI3        /*!< High Speed Low Voltage Pad mode Enable when a SPI3_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SPI4_SIGNAL              SYSCFG_IOCR_HSLVEN_SPI4        /*!< High Speed Low Voltage Pad mode Enable when a SPI4_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SPI5_SIGNAL              SYSCFG_IOCR_HSLVEN_SPI5        /*!< High Speed Low Voltage Pad mode Enable when a SPI5_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SPI6_SIGNAL              SYSCFG_IOCR_HSLVEN_SPI6        /*!< High Speed Low Voltage Pad mode Enable when a SPI6_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SPI7_SIGNAL              SYSCFG_IOCR_HSLVEN_SPI7        /*!< High Speed Low Voltage Pad mode Enable when a SPI7_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_SPI8_SIGNAL              SYSCFG_IOCR_HSLVEN_SPI8        /*!< High Speed Low Voltage Pad mode Enable when a SPI8_x signal is selected in AFMUX */
#define SYSCFG_HIGHSPEED_DCMI_PSSI_DCMIPP_SIGNAL  SYSCFG_IOCR_HSLVEN_DCMI_PSSI   /*!< High Speed Low Voltage Pad mode Enable when a DCMI_PSSI_DCMIPP_x signal is selected in AFMUX */
/**
  * @}
  */
#endif /* SYSCFG_IOCR_HSLVEN_TRACE */

/** @defgroup SYSCFG_Lock_items SYSCFG Lock items
  * @brief SYSCFG items to set lock on
  * @{
  */
#define SYSCFG_NONE                    (0x0U)
#define SYSCFG_SAU                     SYSCFG_M33SSCR_LOCKSAU
#define SYSCFG_MPU_SEC                 SYSCFG_M33SSCR_LOCKSMPU
#define SYSCFG_MPU_NSEC                SYSCFG_M33SSCR_LOCKNSMPU
#define SYSCFG_VTOR_NSEC               SYSCFG_M33SSCR_LOCKNSVTOR
#define SYSCFG_VTOR_AIRCR_SEC          SYSCFG_M33SSCR_LOCKSVTAIRCR
#define SYSCFG_LOCK_ALL                (SYSCFG_MPU_NSEC|SYSCFG_VTOR_NSEC|SYSCFG_SAU|\
                                        SYSCFG_MPU_SEC|SYSCFG_VTOR_AIRCR_SEC)  /*!< All */

#define IS_SYSCFG_LOCK_SELECT(SELECT)  ((((SELECT)) == SYSCFG_NONE)|| \
                                        (((SELECT) & SYSCFG_SAU) == SYSCFG_SAU)|| \
                                        (((SELECT) & SYSCFG_MPU_SEC) == SYSCFG_MPU_SEC)|| \
                                        (((SELECT) & SYSCFG_MPU_NSEC) == SYSCFG_MPU_NSEC)|| \
                                        (((SELECT) & SYSCFG_VTOR_NSEC) == SYSCFG_VTOR_NSEC)|| \
                                        (((SELECT) & SYSCFG_VTOR_AIRCR_SEC) == SYSCFG_VTOR_AIRCR_SEC))
/**
  * @}
  */

/** @defgroup SYSCFG_FPU_Interrupts SYSCFG FPU Interrupts
  * @{
  */
#define SYSCFG_IT_FPU_IDC              SYSCFG_M33SSCR_FPU_IT_EN_5 /*!< Floating Point Unit Input denormal Interrupt */
#define SYSCFG_IT_FPU_IXC              SYSCFG_M33SSCR_FPU_IT_EN_4 /*!< Floating Point Unit Inexact Interrupt */
#define SYSCFG_IT_FPU_UFC              SYSCFG_M33SSCR_FPU_IT_EN_3 /*!< Floating Point Unit Underflow Interrupt */
#define SYSCFG_IT_FPU_OFC              SYSCFG_M33SSCR_FPU_IT_EN_2 /*!< Floating Point Unit Overflow Interrupt */
#define SYSCFG_IT_FPU_DZC              SYSCFG_M33SSCR_FPU_IT_EN_1 /*!< Floating Point Unit Divide-by-zero Interrupt */
#define SYSCFG_IT_FPU_IOC              SYSCFG_M33SSCR_FPU_IT_EN_0 /*!< Floating Point Unit Invalid operation Interrupt */

#define IS_SYSCFG_FPU_INTERRUPT(__INTERRUPT__) ((((__INTERRUPT__) & SYSCFG_IT_FPU_IOC) == SYSCFG_IT_FPU_IOC) || \
                                                (((__INTERRUPT__) & SYSCFG_IT_FPU_DZC) == SYSCFG_IT_FPU_DZC) || \
                                                (((__INTERRUPT__) & SYSCFG_IT_FPU_UFC) == SYSCFG_IT_FPU_UFC) || \
                                                (((__INTERRUPT__) & SYSCFG_IT_FPU_OFC) == SYSCFG_IT_FPU_OFC) || \
                                                (((__INTERRUPT__) & SYSCFG_IT_FPU_IDC) == SYSCFG_IT_FPU_IDC) || \
                                                (((__INTERRUPT__) & SYSCFG_IT_FPU_IXC) == SYSCFG_IT_FPU_IXC))
/**
  * @}
  */

/**
  * @}
  */

/* Exported macro ------------------------------------------------------------*/
/** @defgroup HAL_Exported_Macros HAL Exported Macros
  * @{
  */

/** @defgroup DBG_Exported_Macros DBGMCU Exported Macros
   * @{
   */

/** @brief  Freeze and Unfreeze Peripherals in Debug mode
   */

#if defined (CORE_CA35)
#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH0_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH0()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH0_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH0()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH0_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH0_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH1_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH1()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH1_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH1()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH1_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH1_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH2_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH2()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH2_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH2()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH2_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH2_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH3_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH3()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH3_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH3()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH3_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH3_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH4_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH4()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH4_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH4()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH4_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH4_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH5_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH5()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH5_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH5()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH5_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH5_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH6_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH6()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH6_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH6()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH6_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH6_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH7_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH7()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH7_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH7()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH7_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH7_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH8_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH8()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH8_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH8()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH8_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH8_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH9_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH9()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH9_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH9()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH9_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH9_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH10_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH10()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH10_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH10()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH10_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH10_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH11_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH11()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH11_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH11()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH11_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH11_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH12_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH12()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH12_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH12()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH12_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH12_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH13_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH13()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH13_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH13()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH13_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH13_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH14_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH14()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH14_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH14()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH14_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH14_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH15_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH15()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH15_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH15()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH15_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH15_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH0_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH0()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH0_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH0()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH0_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH0_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH1_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH1()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH1_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH1()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH1_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH1_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH2_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH2()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH2_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH2()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH2_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH2_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH3_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH3()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH3_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH3()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH3_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH3_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH4_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH4()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH4_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH4()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH4_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH4_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH5_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH5()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH5_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH5()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH5_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH5_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH6_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH6()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH6_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH6()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH6_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH6_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH7_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH7()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH7_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH7()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH7_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH7_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH8_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH8()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH8_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH8()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH8_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH8_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH9_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH9()     SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH9_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH9()   CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH9_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH9_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH10_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH10()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH10_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH10()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH10_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH10_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH11_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH11()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH11_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH11()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH11_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH11_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH12_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH12()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH12_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH12()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH12_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH12_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH13_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH13()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH13_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH13()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH13_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH13_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH14_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH14()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH14_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH14()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH14_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH14_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH15_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH15()    SET_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH15_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH15()  CLEAR_BIT(DBGMCU->AHB2LFZ1, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH15_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH15_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH0_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH0()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH0_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH0()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH0_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH0_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH1_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH1()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH1_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH1()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH1_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH1_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH2_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH2()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH2_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH2()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH2_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH2_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH3_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH3()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH3_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH3()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH3_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH3_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH4_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH4()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH4_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH4()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH4_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH4_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH5_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH5()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH5_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH5()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH5_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH5_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH6_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH6()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH6_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH6()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH6_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH6_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH7_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH7()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH7_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH7()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH7_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH7_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH8_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH8()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH8_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH8()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH8_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH8_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH9_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH9()     SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH9_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH9()   CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH9_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH9_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH10_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH10()    SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH10_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH10()  CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH10_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH10_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH11_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH11()    SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH11_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH11()  CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH11_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH11_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH12_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH12()    SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH12_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH12()  CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH12_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH12_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH13_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH13()    SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH13_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH13()  CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH13_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH13_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH14_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH14()    SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH14_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH14()  CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH14_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH14_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH15_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH15()    SET_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH15_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH15()  CLEAR_BIT(DBGMCU->AHB2HFZ1, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH15_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH15_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#define __HAL_DBGMCU_FREEZE_LPDMA_CH0()      SET_BIT(DBGMCU->AHBSRFZ1, DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPDMA_CH0()    CLEAR_BIT(DBGMCU->AHBSRFZ1, DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#define __HAL_DBGMCU_FREEZE_LPDMA_CH1()      SET_BIT(DBGMCU->AHBSRFZ1, DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPDMA_CH1()    CLEAR_BIT(DBGMCU->AHBSRFZ1, DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#define __HAL_DBGMCU_FREEZE_LPDMA_CH2()      SET_BIT(DBGMCU->AHBSRFZ1, DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPDMA_CH2()    CLEAR_BIT(DBGMCU->AHBSRFZ1, DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#define __HAL_DBGMCU_FREEZE_LPDMA_CH3()      SET_BIT(DBGMCU->AHBSRFZ1, DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPDMA_CH3()    CLEAR_BIT(DBGMCU->AHBSRFZ1, DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM2_STOP)
#define __HAL_DBGMCU_FREEZE_TIM2()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM2_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM2()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM2_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM2_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM3_STOP)
#define __HAL_DBGMCU_FREEZE_TIM3()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM3_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM3()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM3_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM3_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM4_STOP)
#define __HAL_DBGMCU_FREEZE_TIM4()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM4_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM4()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM4_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM4_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM5_STOP)
#define __HAL_DBGMCU_FREEZE_TIM5()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM5_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM5()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM5_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM5_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM6_STOP)
#define __HAL_DBGMCU_FREEZE_TIM6()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM6_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM6()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM6_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM6_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM7_STOP)
#define __HAL_DBGMCU_FREEZE_TIM7()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM7_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM7()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM7_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM7_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM10_STOP)
#define __HAL_DBGMCU_FREEZE_TIM10()          SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM10_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM10()        CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM10_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM10_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM11_STOP)
#define __HAL_DBGMCU_FREEZE_TIM11()          SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM11_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM11()        CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM11_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM11_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM12_STOP)
#define __HAL_DBGMCU_FREEZE_TIM12()          SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM12_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM12()        CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM12_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM12_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM13_STOP)
#define __HAL_DBGMCU_FREEZE_TIM13()          SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM13_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM13()        CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM13_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM13_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM14_STOP)
#define __HAL_DBGMCU_FREEZE_TIM14()          SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM14_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM14()        CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_TIM14_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM14_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_LPTIM1_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM1()         SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_LPTIM1_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM1()       CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_LPTIM1_STOP)
#endif /*DBGMCU_APB1FZ_DBG_LPTIM1_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_LPTIM2_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM2()         SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_LPTIM2_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM2()       CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_LPTIM2_STOP)
#endif /*DBGMCU_APB1FZ_DBG_LPTIM2_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C1_STOP)
#define __HAL_DBGMCU_FREEZE_I2C1()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C1_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C1()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C1_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C1_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C2_STOP)
#define __HAL_DBGMCU_FREEZE_I2C2()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C2_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C2()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C2_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C2_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C3_STOP)
#define __HAL_DBGMCU_FREEZE_I2C3()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C3_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C3()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C3_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C3_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C4_STOP)
#define __HAL_DBGMCU_FREEZE_I2C4()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C4_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C4()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C4_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C4_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C5_STOP)
#define __HAL_DBGMCU_FREEZE_I2C5()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C5_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C5()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C5_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C5_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C6_STOP)
#define __HAL_DBGMCU_FREEZE_I2C6()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C6_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C6()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C6_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C6_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C7_STOP)
#define __HAL_DBGMCU_FREEZE_I2C7()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C7_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C7()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I2C7_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C7_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I3C1_STOP)
#define __HAL_DBGMCU_FREEZE_I3C1()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I3C1_STOP)
#define __HAL_DBGMCU_UNFREEZE_I3C1()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I3C1_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I3C1_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I3C2_STOP)
#define __HAL_DBGMCU_FREEZE_I3C2()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I3C2_STOP)
#define __HAL_DBGMCU_UNFREEZE_I3C2()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I3C2_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I3C2_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I3C3_STOP)
#define __HAL_DBGMCU_FREEZE_I3C3()           SET_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I3C3_STOP)
#define __HAL_DBGMCU_UNFREEZE_I3C3()         CLEAR_BIT(DBGMCU->APB1FZ1, DBGMCU_APB1FZ_DBG_I3C3_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I3C3_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM1_STOP)
#define __HAL_DBGMCU_FREEZE_TIM1()           SET_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM1_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM1()         CLEAR_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM1_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM1_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM8_STOP)
#define __HAL_DBGMCU_FREEZE_TIM8()           SET_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM8_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM8()         CLEAR_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM8_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM8_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM15_STOP)
#define __HAL_DBGMCU_FREEZE_TIM15()          SET_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM15_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM15()        CLEAR_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM15_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM15_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM16_STOP)
#define __HAL_DBGMCU_FREEZE_TIM16()          SET_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM16_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM16()        CLEAR_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM16_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM16_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM17_STOP)
#define __HAL_DBGMCU_FREEZE_TIM17()          SET_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM17_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM17()        CLEAR_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM17_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM17_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM20_STOP)
#define __HAL_DBGMCU_FREEZE_TIM20()          SET_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM20_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM20()        CLEAR_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_TIM20_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM20_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_FDCAN_STOP)
#define __HAL_DBGMCU_FREEZE_FDCAN()          SET_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_FDCAN_STOP)
#define __HAL_DBGMCU_UNFREEZE_FDCAN()        CLEAR_BIT(DBGMCU->APB2FZ1, DBGMCU_APB2FZ_DBG_FDCAN_STOP)
#endif /*DBGMCU_APB2FZ_DBG_FDCAN_STOP*/

#if defined(DBGMCU_APB3FZ_DBG_IWDG1_STOP)
#define __HAL_DBGMCU_FREEZE_IWDG1()          SET_BIT(DBGMCU->APB3FZ1, DBGMCU_APB3FZ_DBG_IWDG1_STOP)
#define __HAL_DBGMCU_UNFREEZE_IWDG1()        CLEAR_BIT(DBGMCU->APB3FZ1, DBGMCU_APB3FZ_DBG_IWDG1_STOP)
#endif /*DBGMCU_APB3FZ_DBG_IWDG1_STOP*/

#if defined(DBGMCU_APB3FZ_DBG_IWDG2_STOP)
#define __HAL_DBGMCU_FREEZE_IWDG2()          SET_BIT(DBGMCU->APB3FZ1, DBGMCU_APB3FZ_DBG_IWDG2_STOP)
#define __HAL_DBGMCU_UNFREEZE_IWDG2()        CLEAR_BIT(DBGMCU->APB3FZ1, DBGMCU_APB3FZ_DBG_IWDG2_STOP)
#endif /*DBGMCU_APB3FZ_DBG_IWDG2_STOP*/

#if defined(DBGMCU_APB3FZ_DBG_WWDG1_STOP)
#define __HAL_DBGMCU_FREEZE_WWDG1()          SET_BIT(DBGMCU->APB3FZ1, DBGMCU_APB3FZ_DBG_WWDG1_STOP)
#define __HAL_DBGMCU_UNFREEZE_WWDG1()        CLEAR_BIT(DBGMCU->APB3FZ1, DBGMCU_APB3FZ_DBG_WWDG1_STOP)
#endif /*DBGMCU_APB3FZ_DBG_WWDG1_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_RTC_STOP)
#define __HAL_DBGMCU_FREEZE_RTC()           SET_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_RTC_STOP)
#define __HAL_DBGMCU_UNFREEZE_RTC()         CLEAR_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_RTC_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_RTC_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#define __HAL_DBGMCU_FREEZE_I2C8()           SET_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C8()         CLEAR_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_I2C8_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#define __HAL_DBGMCU_FREEZE_I3C4()           SET_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#define __HAL_DBGMCU_UNFREEZE_I3C4()         CLEAR_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_I3C4_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM3()         SET_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM3()       CLEAR_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM3_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM4()         SET_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM4()       CLEAR_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM4_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM5()         SET_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM5()       CLEAR_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM5_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#define __HAL_DBGMCU_FREEZE_WWDG2()          SET_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#define __HAL_DBGMCU_UNFREEZE_WWDG2()        CLEAR_BIT(DBGMCU->APBSRFZ1, DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_WWDG2_STOP*/

#if defined(DBGMCU_CRA35_DBG_STGEN_STOP)
#define __HAL_DBGMCU_FREEZE_STGEN()          SET_BIT(DBGMCU->CRA35, DBGMCU_CRA35_DBG_STGEN_STOP)
#define __HAL_DBGMCU_UNFREEZE_STGEN()        CLEAR_BIT(DBGMCU->CRA35, DBGMCU_CRA35_DBG_STGEN_STOP)
#endif /*DBGMCU_CRA35_DBG_STGEN_STOP*/
#elif defined (CORE_CM33)
#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH0_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH0()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH0_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH0()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH0_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH0_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH1_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH1()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH1_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH1()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH1_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH1_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH2_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH2()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH2_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH2()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH2_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH2_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH3_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH3()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH3_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH3()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH3_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH3_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH4_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH4()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH4_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH4()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH4_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH4_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH5_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH5()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH5_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH5()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH5_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH5_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH6_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH6()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH6_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH6()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH6_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH6_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH7_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH7()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH7_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH7()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH7_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH7_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH8_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH8()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH8_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH8()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH8_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH8_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH9_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH9()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH9_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH9()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH9_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH9_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH10_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH10()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH10_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH10()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH10_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH10_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH11_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH11()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH11_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH11()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH11_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH11_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH12_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH12()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH12_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH12()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH12_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH12_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH13_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH13()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH13_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH13()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH13_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH13_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH14_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH14()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH14_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH14()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH14_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH14_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA1_CH15_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA1_CH15()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH15_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA1_CH15()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA1_CH15_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA1_CH15_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH0_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH0()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH0_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH0()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH0_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH0_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH1_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH1()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH1_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH1()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH1_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH1_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH2_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH2()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH2_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH2()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH2_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH2_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH3_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH3()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH3_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH3()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH3_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH3_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH4_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH4()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH4_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH4()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH4_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH4_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH5_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH5()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH5_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH5()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH5_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH5_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH6_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH6()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH6_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH6()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH6_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH6_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH7_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH7()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH7_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH7()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH7_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH7_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH8_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH8()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH8_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH8()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH8_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH8_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH9_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH9()     SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH9_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH9()   CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH9_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH9_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH10_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH10()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH10_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH10()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH10_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH10_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH11_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH11()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH11_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH11()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH11_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH11_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH12_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH12()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH12_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH12()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH12_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH12_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH13_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH13()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH13_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH13()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH13_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH13_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH14_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH14()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH14_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH14()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH14_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH14_STOP*/

#if defined(DBGMCU_AHB2LFZ_DBG_HPDMA2_CH15_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA2_CH15()    SET_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH15_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA2_CH15()  CLEAR_BIT(DBGMCU->AHB2LFZ2, DBGMCU_AHB2LFZ_DBG_HPDMA2_CH15_STOP)
#endif /*DBGMCU_AHB2LFZ_DBG_HPDMA2_CH15_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH0_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH0()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH0_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH0()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH0_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH0_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH1_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH1()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH1_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH1()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH1_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH1_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH2_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH2()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH2_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH2()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH2_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH2_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH3_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH3()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH3_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH3()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH3_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH3_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH4_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH4()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH4_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH4()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH4_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH4_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH5_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH5()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH5_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH5()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH5_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH5_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH6_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH6()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH6_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH6()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH6_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH6_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH7_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH7()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH7_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH7()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH7_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH7_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH8_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH8()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH8_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH8()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH8_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH8_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH9_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH9()     SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH9_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH9()   CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH9_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH9_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH10_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH10()    SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH10_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH10()  CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH10_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH10_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH11_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH11()    SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH11_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH11()  CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH11_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH11_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH12_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH12()    SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH12_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH12()  CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH12_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH12_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH13_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH13()    SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH13_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH13()  CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH13_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH13_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH14_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH14()    SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH14_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH14()  CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH14_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH14_STOP*/

#if defined(DBGMCU_AHB2HFZ_DBG_HPDMA3_CH15_STOP)
#define __HAL_DBGMCU_FREEZE_HPDMA3_CH15()    SET_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH15_STOP)
#define __HAL_DBGMCU_UNFREEZE_HPDMA3_CH15()  CLEAR_BIT(DBGMCU->AHB2HFZ2, DBGMCU_AHB2HFZ_DBG_HPDMA3_CH15_STOP)
#endif /*DBGMCU_AHB2HFZ_DBG_HPDMA3_CH15_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#define __HAL_DBGMCU_FREEZE_LPDMA_CH0()      SET_BIT(DBGMCU->AHBSRFZ2, DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPDMA_CH0()    CLEAR_BIT(DBGMCU->AHBSRFZ2, DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#define __HAL_DBGMCU_FREEZE_LPDMA_CH1()      SET_BIT(DBGMCU->AHBSRFZ2, DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPDMA_CH1()    CLEAR_BIT(DBGMCU->AHBSRFZ2, DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#define __HAL_DBGMCU_FREEZE_LPDMA_CH2()      SET_BIT(DBGMCU->AHBSRFZ2, DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPDMA_CH2()    CLEAR_BIT(DBGMCU->AHBSRFZ2, DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#define __HAL_DBGMCU_FREEZE_LPDMA_CH3()      SET_BIT(DBGMCU->AHBSRFZ2, DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPDMA_CH3()    CLEAR_BIT(DBGMCU->AHBSRFZ2, DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#define __HAL_DBGMCU_C3_FREEZE_LPDMA_CH0()   SET_BIT(DBGMCU->AHBSRFZ3, DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_LPDMA_CH0() CLEAR_BIT(DBGMCU->AHBSRFZ3, DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH0_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#define __HAL_DBGMCU_C3_FREEZE_LPDMA_CH1()   SET_BIT(DBGMCU->AHBSRFZ3, DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_LPDMA_CH1() CLEAR_BIT(DBGMCU->AHBSRFZ3, DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH1_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#define __HAL_DBGMCU_C3_FREEZE_LPDMA_CH2()   SET_BIT(DBGMCU->AHBSRFZ3, DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_LPDMA_CH2() CLEAR_BIT(DBGMCU->AHBSRFZ3, DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH2_STOP*/

#if defined(DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#define __HAL_DBGMCU_C3_FREEZE_LPDMA_CH3()   SET_BIT(DBGMCU->AHBSRFZ3, DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_LPDMA_CH3() CLEAR_BIT(DBGMCU->AHBSRFZ3, DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP)
#endif /*DBGMCU_AHBSRFZ_DBG_LPDMA_CH3_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM2_STOP)
#define __HAL_DBGMCU_FREEZE_TIM2()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM2_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM2()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM2_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM2_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM3_STOP)
#define __HAL_DBGMCU_FREEZE_TIM3()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM3_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM3()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM3_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM3_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM4_STOP)
#define __HAL_DBGMCU_FREEZE_TIM4()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM4_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM4()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM4_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM4_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM5_STOP)
#define __HAL_DBGMCU_FREEZE_TIM5()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM5_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM5()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM5_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM5_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM6_STOP)
#define __HAL_DBGMCU_FREEZE_TIM6()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM6_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM6()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM6_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM6_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM7_STOP)
#define __HAL_DBGMCU_FREEZE_TIM7()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM7_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM7()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM7_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM7_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM10_STOP)
#define __HAL_DBGMCU_FREEZE_TIM10()          SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM10_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM10()        CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM10_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM10_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM11_STOP)
#define __HAL_DBGMCU_FREEZE_TIM11()          SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM11_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM11()        CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM11_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM11_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM12_STOP)
#define __HAL_DBGMCU_FREEZE_TIM12()          SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM12_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM12()        CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM12_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM12_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM13_STOP)
#define __HAL_DBGMCU_FREEZE_TIM13()          SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM13_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM13()        CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM13_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM13_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_TIM14_STOP)
#define __HAL_DBGMCU_FREEZE_TIM14()          SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM14_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM14()        CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_TIM14_STOP)
#endif /*DBGMCU_APB1FZ_DBG_TIM14_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_LPTIM1_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM1()         SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_LPTIM1_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM1()       CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_LPTIM1_STOP)
#endif /*DBGMCU_APB1FZ_DBG_LPTIM1_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_LPTIM2_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM2()         SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_LPTIM2_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM2()       CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_LPTIM2_STOP)
#endif /*DBGMCU_APB1FZ_DBG_LPTIM2_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C1_STOP)
#define __HAL_DBGMCU_FREEZE_I2C1()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C1_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C1()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C1_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C1_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C2_STOP)
#define __HAL_DBGMCU_FREEZE_I2C2()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C2_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C2()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C2_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C2_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C3_STOP)
#define __HAL_DBGMCU_FREEZE_I2C3()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C3_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C3()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C3_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C3_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C4_STOP)
#define __HAL_DBGMCU_FREEZE_I2C4()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C4_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C4()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C4_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C4_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C5_STOP)
#define __HAL_DBGMCU_FREEZE_I2C5()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C5_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C5()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C5_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C5_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C6_STOP)
#define __HAL_DBGMCU_FREEZE_I2C6()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C6_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C6()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C6_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C6_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I2C7_STOP)
#define __HAL_DBGMCU_FREEZE_I2C7()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C7_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C7()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I2C7_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I2C7_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I3C1_STOP)
#define __HAL_DBGMCU_FREEZE_I3C1()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I3C1_STOP)
#define __HAL_DBGMCU_UNFREEZE_I3C1()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I3C1_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I3C1_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I3C2_STOP)
#define __HAL_DBGMCU_FREEZE_I3C2()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I3C2_STOP)
#define __HAL_DBGMCU_UNFREEZE_I3C2()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I3C2_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I3C2_STOP*/

#if defined(DBGMCU_APB1FZ_DBG_I3C3_STOP)
#define __HAL_DBGMCU_FREEZE_I3C3()           SET_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I3C3_STOP)
#define __HAL_DBGMCU_UNFREEZE_I3C3()         CLEAR_BIT(DBGMCU->APB1FZ2, DBGMCU_APB1FZ_DBG_I3C3_STOP)
#endif /*DBGMCU_APB1FZ_DBG_I3C3_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM1_STOP)
#define __HAL_DBGMCU_FREEZE_TIM1()           SET_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM1_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM1()         CLEAR_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM1_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM1_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM8_STOP)
#define __HAL_DBGMCU_FREEZE_TIM8()           SET_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM8_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM8()         CLEAR_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM8_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM8_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM15_STOP)
#define __HAL_DBGMCU_FREEZE_TIM15()          SET_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM15_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM15()        CLEAR_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM15_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM15_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM16_STOP)
#define __HAL_DBGMCU_FREEZE_TIM16()          SET_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM16_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM16()        CLEAR_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM16_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM16_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM17_STOP)
#define __HAL_DBGMCU_FREEZE_TIM17()          SET_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM17_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM17()        CLEAR_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM17_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM17_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_TIM20_STOP)
#define __HAL_DBGMCU_FREEZE_TIM20()          SET_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM20_STOP)
#define __HAL_DBGMCU_UNFREEZE_TIM20()        CLEAR_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_TIM20_STOP)
#endif /*DBGMCU_APB2FZ_DBG_TIM20_STOP*/

#if defined(DBGMCU_APB2FZ_DBG_FDCAN_STOP)
#define __HAL_DBGMCU_FREEZE_FDCAN()          SET_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_FDCAN_STOP)
#define __HAL_DBGMCU_UNFREEZE_FDCAN()        CLEAR_BIT(DBGMCU->APB2FZ2, DBGMCU_APB2FZ_DBG_FDCAN_STOP)
#endif /*DBGMCU_APB2FZ_DBG_FDCAN_STOP*/

#if defined(DBGMCU_APB3FZ_DBG_IWDG3_STOP)
#define __HAL_DBGMCU_FREEZE_IWDG3()          SET_BIT(DBGMCU->APB3FZ2, DBGMCU_APB3FZ_DBG_IWDG3_STOP)
#define __HAL_DBGMCU_UNFREEZE_IWDG3()        CLEAR_BIT(DBGMCU->APB3FZ2, DBGMCU_APB3FZ_DBG_IWDG3_STOP)
#endif /*DBGMCU_APB3FZ_DBG_IWDG3_STOP*/

#if defined(DBGMCU_APB3FZ_DBG_IWDG4_STOP)
#define __HAL_DBGMCU_FREEZE_IWDG4()          SET_BIT(DBGMCU->APB3FZ2, DBGMCU_APB3FZ_DBG_IWDG4_STOP)
#define __HAL_DBGMCU_UNFREEZE_IWDG4()        CLEAR_BIT(DBGMCU->APB3FZ2, DBGMCU_APB3FZ_DBG_IWDG4_STOP)
#endif /*DBGMCU_APB3FZ_DBG_IWDG4_STOP*/

#if defined(DBGMCU_APB3FZ_DBG_WWDG1_STOP)
#define __HAL_DBGMCU_FREEZE_WWDG1()          SET_BIT(DBGMCU->APB3FZ2, DBGMCU_APB3FZ_DBG_WWDG1_STOP)
#define __HAL_DBGMCU_UNFREEZE_WWDG1()        CLEAR_BIT(DBGMCU->APB3FZ2, DBGMCU_APB3FZ_DBG_WWDG1_STOP)
#endif /*DBGMCU_APB3FZ_DBG_WWDG1_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_RTC_STOP)
#define __HAL_DBGMCU_FREEZE_RTC()           SET_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_RTC_STOP)
#define __HAL_DBGMCU_UNFREEZE_RTC()         CLEAR_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_RTC_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_RTC_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#define __HAL_DBGMCU_FREEZE_I2C8()           SET_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#define __HAL_DBGMCU_UNFREEZE_I2C8()         CLEAR_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_I2C8_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#define __HAL_DBGMCU_FREEZE_I3C4()           SET_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#define __HAL_DBGMCU_UNFREEZE_I3C4()         CLEAR_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_I3C4_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM3()         SET_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM3()       CLEAR_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM3_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM4()         SET_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM4()       CLEAR_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM4_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#define __HAL_DBGMCU_FREEZE_LPTIM5()         SET_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#define __HAL_DBGMCU_UNFREEZE_LPTIM5()       CLEAR_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM5_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#define __HAL_DBGMCU_FREEZE_WWDG2()          SET_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#define __HAL_DBGMCU_UNFREEZE_WWDG2()        CLEAR_BIT(DBGMCU->APBSRFZ2, DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_WWDG2_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_RTC_STOP)
#define __HAL_DBGMCU_C3_FREEZE_RTC()         SET_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_RTC_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_RTC()       CLEAR_BIT(DBGMCU->APB1FZ3, DBGMCU_APBSRFZ_DBG_RTC_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_RTC_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#define __HAL_DBGMCU_C3_FREEZE_I2C8()        SET_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_I2C8()      CLEAR_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_I2C8_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_I2C8_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#define __HAL_DBGMCU_C3_FREEZE_I3C4()        SET_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_I3C4()      CLEAR_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_I3C4_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_I3C4_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#define __HAL_DBGMCU_C3_FREEZE_LPTIM3()      SET_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_LPTIM3()    CLEAR_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_LPTIM3_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM3_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#define __HAL_DBGMCU_C3_FREEZE_LPTIM4()      SET_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_LPTIM4()    CLEAR_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_LPTIM4_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM4_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#define __HAL_DBGMCU_C3_FREEZE_LPTIM5()      SET_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_LPTIM5()    CLEAR_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_LPTIM5_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_LPTIM4_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_IWDG5_STOP)
#define __HAL_DBGMCU_C3_FREEZE_IWDG5()       SET_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_IWDG5_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_IWDG5()     CLEAR_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_IWDG5_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_IWDG5_STOP*/

#if defined(DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#define __HAL_DBGMCU_C3_FREEZE_WWDG2()       SET_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#define __HAL_DBGMCU_C3_UNFREEZE_WWDG2()     CLEAR_BIT(DBGMCU->APBSRFZ3, DBGMCU_APBSRFZ_DBG_WWDG2_STOP)
#endif /*DBGMCU_APBSRFZ_DBG_WWDG2_STOP*/
#endif /* Cores */

/**
  * @}
  */

/** @defgroup SYSCFG_Exported_Macros SYSCFG Exported Macros
  * @{
  */
#if defined(CORE_CA35) || defined(CORE_CM33)
/** @brief  Floating Point Unit interrupt enable/disable macros
  * @param __INTERRUPT__  This parameter can be a value of @ref SYSCFG_FPU_Interrupts
  *   @arg SYSCFG_IT_FPU_IDC
  *   @arg SYSCFG_IT_FPU_IXC
  *   @arg SYSCFG_IT_FPU_UFC
  *   @arg SYSCFG_IT_FPU_OFC
  *   @arg SYSCFG_IT_FPU_DZC
  *   @arg SYSCFG_IT_FPU_IOC
  */
#define __HAL_SYSCFG_FPU_INTERRUPT_ENABLE(__INTERRUPT__)    do {assert_param(IS_SYSCFG_FPU_INTERRUPT((__INTERRUPT__)));\
                                                                 SET_BIT(SYSCFG->M33SSCR, (__INTERRUPT__));\
                                                               }while(0)

#define __HAL_SYSCFG_FPU_INTERRUPT_DISABLE(__INTERRUPT__)   do {assert_param(IS_SYSCFG_FPU_INTERRUPT((__INTERRUPT__)));\
                                                                 CLEAR_BIT(SYSCFG->M33SSCR, (__INTERRUPT__));\
                                                               }while(0)
#endif /* CORE_CA35 || CORE_CM33 */
/**
  * @}
  */

/**
  * @}
  */

/* Exported functions --------------------------------------------------------*/
/** @addtogroup HAL_Exported_Functions
  * @{
  */

/** @addtogroup HAL_Exported_Functions_Group1
  * @{
  */
/* Initialization and de-initialization functions  ******************************/
HAL_StatusTypeDef     HAL_Init(void);
HAL_StatusTypeDef     HAL_DeInit(void);
void                  HAL_MspInit(void);
void                  HAL_MspDeInit(void);
HAL_StatusTypeDef     HAL_InitTick(uint32_t TickPriority);
/**
  * @}
  */

/** @addtogroup HAL_Exported_Functions_Group2
  * @{
  */
/* Peripheral Control functions  ************************************************/
void                  HAL_IncTick(void);
void                  HAL_Delay(__IO uint32_t Delay);
uint32_t              HAL_GetTick(void);
void                  HAL_SuspendTick(void);
void                  HAL_ResumeTick(void);
uint32_t              HAL_GetHalVersion(void);
#if defined(CORE_CA35) || defined(CORE_CM33)
uint32_t              HAL_GetREVID(void);
uint32_t              HAL_GetDEVID(void);
uint32_t              HAL_GetUIDw0(void);
uint32_t              HAL_GetUIDw1(void);
uint32_t              HAL_GetUIDw2(void);
/**
  * @}
  */

/** @addtogroup HAL_Exported_Functions_Group3
  * @{
  */

/* DBGMCU Peripheral Control functions  ***************************************/
void                  HAL_DBGMCU_EnableWatchdogTimer2CA35Freeze(void);
void                  HAL_DBGMCU_DisableWatchdogTimer2CA35Freeze(void);
void                  HAL_DBGMCU_EnableDBGSleepMode(void);
void                  HAL_DBGMCU_DisableDBGSleepMode(void);
void                  HAL_DBGMCU_EnableDBGStopMode(void);
void                  HAL_DBGMCU_DisableDBGStopMode(void);
void                  HAL_DBGMCU_EnableDBGStandbyMode(void);
void                  HAL_DBGMCU_DisableDBGStandbyMode(void);
/**
  * @}
  */

/** @addtogroup HAL_Exported_Functions_Group4
  * @{
  */
/* SYSCFG Peripheral Control functions  ***************************************/
void                  HAL_HDP_DisableHDP(void);
void                  HAL_HDP_EnableHDP(void);
void                  HAL_HDP_ConfigHDPMux(uint32_t HDP_Mux, uint32_t HDP_Signal);
void                  HAL_HDP_WriteGPOVAL(uint32_t GPOVAL_value);
uint32_t              HAL_HDP_ReadVAL(void);
/**
  * @}
  */

/** @addtogroup HAL_Exported_Functions_Group5
  * @{
  */

/* SYSCFG Peripheral Control functions  ***************************************/
void                  HAL_SYSCFG_ETH1InterfaceSelect(uint32_t SYSCFG_ETHInterface);
void                  HAL_SYSCFG_ETH2InterfaceSelect(uint32_t SYSCFG_ETHInterface);
void                  HAL_SYSCFG_ETH1ClockSelect(uint32_t SYSCFG_ETHClock);
void                  HAL_SYSCFG_ETH2ClockSelect(uint32_t SYSCFG_ETHClock);
void                  HAL_SYSCFG_AnalogSwitchConfig(uint32_t SYSCFG_AnalogSwitch, uint32_t SYSCFG_SwitchState);
void                  HAL_SYSCFG_EnableIOSpeedOptimize(uint32_t SYSCFG_HighSpeedSignal);
void                  HAL_SYSCFG_DisableIOSpeedOptimize(uint32_t SYSCFG_HighSpeedSignal);
void                  HAL_SYSCFG_Lock(uint32_t Item);
HAL_StatusTypeDef     HAL_SYSCFG_GetLock(uint32_t *pItem);
/**
  * @}
  */
#endif /* CORE_CA35 || CORE_CM33 */
/**
  * @}
  */

/**
  * @}
  */
/**
  * @}
  */

#ifdef __cplusplus
}
#endif

#endif /* __STM32MP2xx_HAL_H */
