name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          pip3 install -r scripts/requirements.txt
          pip3 install -r scripts/requirements-test.txt
          pip3 install -r scripts/requirements-dev.txt
      - name: lint scripts
        run: flake8 --config scripts/.flake8 scripts
      - name: run script tests
        run: |
          pytest scripts/tests \
            --cov=scripts \
            --cov-config scripts/.coveragerc \
            --cov-report term \
            --cov-report html \
            -vv
      - name: store coverage report 
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: htmlcov
